23/06/17 08:42:35 INFO client.RMProxy: Connecting to ResourceManager at /127.0.0.1:8032
23/06/17 08:42:37 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
23/06/17 08:42:39 INFO input.FileInputFormat: Total input paths to process : 16
23/06/17 08:42:39 INFO mapreduce.JobSubmitter: number of splits:16
23/06/17 08:42:40 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1687012830798_0001
23/06/17 08:42:42 INFO impl.YarnClientImpl: Submitted application application_1687012830798_0001
23/06/17 08:42:42 INFO mapreduce.Job: The url to track the job: http://pcvm606-5.emulab.net:8088/proxy/application_1687012830798_0001/
23/06/17 08:42:42 INFO mapreduce.Job: Running job: job_1687012830798_0001
23/06/17 08:43:05 INFO mapreduce.Job: Job job_1687012830798_0001 running in uber mode : false
23/06/17 08:43:05 INFO mapreduce.Job:  map 0% reduce 0%
23/06/17 08:52:34 INFO mapreduce.Job:  map 6% reduce 0%
23/06/17 08:53:18 INFO mapreduce.Job:  map 13% reduce 0%
23/06/17 08:53:35 INFO mapreduce.Job:  map 94% reduce 0%
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000002_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000002_0 Timed out after 600 secs
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000004_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000004_0 Timed out after 600 secs
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000000_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000000_0 Timed out after 600 secs
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000001_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000001_0 Timed out after 600 secs
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000003_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000003_0 Timed out after 600 secs
23/06/17 08:54:33 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000005_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000005_0 Timed out after 600 secs
23/06/17 08:54:34 INFO mapreduce.Job:  map 44% reduce 0%
23/06/17 08:54:34 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000013_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000013_0 Timed out after 600 secs
cleanup failed for container container_1687012830798_0001_01_000015 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34626 remote=pcvm603-6.emulab.net/172.20.3.6:46197]; Host Details : local host is: "slave0.hadoop-ljf.mapreduce630.emulab.net/172.20.4.3"; destination host is: "pcvm603-6.emulab.net":46197; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.stopContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.stopContainers(ContainerManagementProtocolPBClientImpl.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.stopContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.kill(ContainerLauncherImpl.java:207)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34626 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 16 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34626 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 19 more

23/06/17 08:54:34 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000014_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000014_0 Timed out after 600 secs
cleanup failed for container container_1687012830798_0001_01_000016 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34628 remote=pcvm603-6.emulab.net/172.20.3.6:46197]; Host Details : local host is: "slave0.hadoop-ljf.mapreduce630.emulab.net/172.20.4.3"; destination host is: "pcvm603-6.emulab.net":46197; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.stopContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.stopContainers(ContainerManagementProtocolPBClientImpl.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.stopContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.kill(ContainerLauncherImpl.java:207)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34628 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 16 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34628 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 19 more

23/06/17 08:54:34 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000006_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000006_0 Timed out after 600 secs
23/06/17 08:54:35 INFO mapreduce.Job:  map 38% reduce 0%
23/06/17 08:54:36 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000012_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000012_0 Timed out after 600 secs
cleanup failed for container container_1687012830798_0001_01_000014 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34636 remote=pcvm603-6.emulab.net/172.20.3.6:46197]; Host Details : local host is: "slave0.hadoop-ljf.mapreduce630.emulab.net/172.20.4.3"; destination host is: "pcvm603-6.emulab.net":46197; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.stopContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.stopContainers(ContainerManagementProtocolPBClientImpl.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.stopContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.kill(ContainerLauncherImpl.java:207)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34636 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 16 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.4.3:34636 remote=pcvm603-6.emulab.net/172.20.3.6:46197]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 19 more

23/06/17 08:54:37 INFO mapreduce.Job:  map 31% reduce 0%
23/06/17 08:54:50 INFO mapreduce.Job:  map 35% reduce 0%
23/06/17 08:54:51 INFO mapreduce.Job:  map 38% reduce 0%
23/06/17 08:55:58 INFO mapreduce.Job:  map 19% reduce 0%
23/06/17 08:55:59 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000010_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000010_0 Timed out after 600 secs
23/06/17 08:55:59 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000011_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000011_0 Timed out after 600 secs
23/06/17 08:55:59 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000009_0, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000009_0 Timed out after 600 secs
23/06/17 09:02:30 INFO mapreduce.Job:  map 25% reduce 0%
23/06/17 09:02:31 INFO mapreduce.Job:  map 69% reduce 0%
23/06/17 09:03:01 INFO mapreduce.Job:  map 75% reduce 0%
23/06/17 09:03:20 INFO mapreduce.Job:  map 81% reduce 0%
23/06/17 09:03:27 INFO mapreduce.Job:  map 85% reduce 0%
23/06/17 09:03:28 INFO mapreduce.Job:  map 88% reduce 0%
23/06/17 09:04:35 INFO mapreduce.Job:  map 94% reduce 0%
23/06/17 09:04:39 INFO mapreduce.Job:  map 92% reduce 0%
23/06/17 09:04:50 INFO mapreduce.Job:  map 73% reduce 6%
23/06/17 09:04:54 INFO mapreduce.Job:  map 67% reduce 6%
23/06/17 09:04:54 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000003_2, Status : FAILED
23/06/17 09:04:54 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000011_1, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000001_2, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000010_1, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000005_2, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000012_2, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000014_1, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000005_1, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000014_2, Status : FAILED
23/06/17 09:04:55 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000009_1, Status : FAILED
23/06/17 09:05:15 INFO mapreduce.Job:  map 69% reduce 6%
23/06/17 09:05:16 INFO mapreduce.Job: Task Id : attempt_1687012830798_0001_m_000000_2, Status : FAILED
AttemptID:attempt_1687012830798_0001_m_000000_2 Timed out after 600 secs
23/06/17 09:05:17 INFO mapreduce.Job:  map 67% reduce 6%
23/06/17 09:05:18 INFO mapreduce.Job:  map 69% reduce 6%
23/06/17 09:05:19 INFO mapreduce.Job:  map 69% reduce 19%
23/06/17 09:05:22 INFO mapreduce.Job:  map 75% reduce 19%
23/06/17 09:05:26 INFO mapreduce.Job:  map 75% reduce 21%
23/06/17 09:05:28 INFO mapreduce.Job:  map 81% reduce 21%
23/06/17 09:05:30 INFO mapreduce.Job:  map 81% reduce 23%
23/06/17 09:05:39 INFO mapreduce.Job:  map 81% reduce 27%
23/06/17 09:05:56 INFO mapreduce.Job:  map 88% reduce 27%
23/06/17 09:05:58 INFO mapreduce.Job:  map 88% reduce 29%
23/06/17 09:06:52 INFO mapreduce.Job:  map 94% reduce 29%
23/06/17 09:06:57 INFO mapreduce.Job:  map 94% reduce 31%
23/06/17 09:07:00 INFO mapreduce.Job:  map 100% reduce 31%
23/06/17 09:07:03 INFO mapreduce.Job:  map 100% reduce 33%
23/06/17 09:07:21 INFO mapreduce.Job:  map 100% reduce 67%
23/06/17 09:07:29 INFO mapreduce.Job:  map 100% reduce 100%
23/06/17 09:07:42 INFO mapreduce.Job: Job job_1687012830798_0001 completed successfully
23/06/17 09:07:43 INFO mapred.ClientServiceDelegate: Application state is completed. FinalApplicationStatus=SUCCEEDED. Redirecting to job history server
23/06/17 09:08:10 INFO mapred.ClientServiceDelegate: Application state is completed. FinalApplicationStatus=SUCCEEDED. Redirecting to job history server
23/06/17 09:08:10 INFO mapred.ClientServiceDelegate: Application state is completed. FinalApplicationStatus=SUCCEEDED. Redirecting to job history server
Exception in thread "main" java.io.IOException: java.io.IOException: Unknown Job job_1687012830798_0001
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.verifyAndGetJob(HistoryClientService.java:218)
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.getCounters(HistoryClientService.java:232)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.service.MRClientProtocolPBServiceImpl.getCounters(MRClientProtocolPBServiceImpl.java:159)
	at org.apache.hadoop.yarn.proto.MRClientProtocol$MRClientProtocolService$2.callBlockingMethod(MRClientProtocol.java:281)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:344)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobCounters(ClientServiceDelegate.java:382)
	at org.apache.hadoop.mapred.YARNRunner.getJobCounters(YARNRunner.java:590)
	at org.apache.hadoop.mapreduce.Job$7.run(Job.java:761)
	at org.apache.hadoop.mapreduce.Job$7.run(Job.java:758)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.mapreduce.Job.getCounters(Job.java:758)
	at org.apache.hadoop.mapreduce.Job.monitorAndPrintJob(Job.java:1383)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1311)
	at wordcount.WordCount.main(WordCount.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.io.IOException: Unknown Job job_1687012830798_0001
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.verifyAndGetJob(HistoryClientService.java:218)
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.getCounters(HistoryClientService.java:232)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.service.MRClientProtocolPBServiceImpl.getCounters(MRClientProtocolPBServiceImpl.java:159)
	at org.apache.hadoop.yarn.proto.MRClientProtocol$MRClientProtocolService$2.callBlockingMethod(MRClientProtocol.java:281)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.ipc.RemoteException.instantiateException(RemoteException.java:106)
	at org.apache.hadoop.ipc.RemoteException.unwrapRemoteException(RemoteException.java:95)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.unwrapAndThrowException(MRClientProtocolPBClientImpl.java:291)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getCounters(MRClientProtocolPBClientImpl.java:168)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:325)
	... 17 more
Caused by: org.apache.hadoop.ipc.RemoteException(java.io.IOException): Unknown Job job_1687012830798_0001
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.verifyAndGetJob(HistoryClientService.java:218)
	at org.apache.hadoop.mapreduce.v2.hs.HistoryClientService$HSClientProtocolHandler.getCounters(HistoryClientService.java:232)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.service.MRClientProtocolPBServiceImpl.getCounters(MRClientProtocolPBServiceImpl.java:159)
	at org.apache.hadoop.yarn.proto.MRClientProtocol$MRClientProtocolService$2.callBlockingMethod(MRClientProtocol.java:281)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:616)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:982)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2217)
	at org.apache.hadoop.ipc.Server$Handler$1.run(Server.java:2213)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2213)

	at org.apache.hadoop.ipc.Client.call(Client.java:1476)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy15.getCounters(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getCounters(MRClientProtocolPBClientImpl.java:166)
	... 22 more
