23/06/17 01:56:59 INFO client.RMProxy: Connecting to ResourceManager at /127.0.0.1:8032
23/06/17 01:57:00 WARN mapreduce.JobResourceUploader: Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
23/06/17 01:57:01 INFO input.FileInputFormat: Total input paths to process : 31
23/06/17 01:57:01 INFO mapreduce.JobSubmitter: number of splits:31
23/06/17 01:57:01 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_1686987427129_0002
23/06/17 01:57:02 INFO impl.YarnClientImpl: Submitted application application_1686987427129_0002
23/06/17 01:57:03 INFO mapreduce.Job: The url to track the job: http://pcvm604-9.emulab.net:8088/proxy/application_1686987427129_0002/
23/06/17 01:57:03 INFO mapreduce.Job: Running job: job_1686987427129_0002
23/06/17 01:57:18 INFO mapreduce.Job: Job job_1686987427129_0002 running in uber mode : false
23/06/17 01:57:18 INFO mapreduce.Job:  map 0% reduce 0%
23/06/17 02:08:14 INFO mapreduce.Job:  map 16% reduce 0%
23/06/17 02:08:23 INFO mapreduce.Job:  map 45% reduce 0%
23/06/17 02:08:43 INFO mapreduce.Job:  map 48% reduce 0%
23/06/17 02:08:46 INFO mapreduce.Job:  map 54% reduce 0%
23/06/17 02:09:11 INFO mapreduce.Job:  map 55% reduce 0%
23/06/17 02:09:47 INFO mapreduce.Job:  map 57% reduce 0%
23/06/17 02:09:50 INFO mapreduce.Job:  map 58% reduce 0%
23/06/17 02:09:52 INFO mapreduce.Job:  map 61% reduce 0%
23/06/17 02:10:23 INFO mapreduce.Job:  map 65% reduce 0%
23/06/17 02:10:25 INFO mapreduce.Job:  map 68% reduce 0%
23/06/17 02:10:28 INFO mapreduce.Job:  map 70% reduce 0%
23/06/17 02:10:29 INFO mapreduce.Job:  map 71% reduce 0%
23/06/17 02:10:38 INFO mapreduce.Job:  map 52% reduce 0%
23/06/17 02:10:38 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000018_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000018_0 Timed out after 600 secs
Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

23/06/17 02:10:39 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000019_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000019_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000021
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:10:39 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000002_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000002_0 Timed out after 600 secs
23/06/17 02:10:39 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000014_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000014_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000016
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:10:39 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000016_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000016_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000018
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:10:39 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000000_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000000_0 Timed out after 600 secs
23/06/17 02:10:40 INFO mapreduce.Job:  map 48% reduce 0%
23/06/17 02:10:40 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000017_0, Status : FAILED
Container killed on request. Exit code is 137
Container exited with a non-zero exit code 137
Killed by external signal

23/06/17 02:11:01 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000013_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000013_0 Timed out after 600 secs
23/06/17 02:11:02 INFO mapreduce.Job:  map 45% reduce 0%
23/06/17 02:11:02 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000010_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000010_0 Timed out after 600 secs
23/06/17 02:11:02 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000006_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000006_0 Timed out after 600 secs
23/06/17 02:11:02 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000012_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000012_0 Timed out after 600 secs
23/06/17 02:11:04 INFO mapreduce.Job:  map 23% reduce 0%
23/06/17 02:11:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000011_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000011_0 Timed out after 600 secs
23/06/17 02:11:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000009_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000009_0 Timed out after 600 secs
23/06/17 02:11:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000008_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000008_0 Timed out after 600 secs
23/06/17 02:11:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000007_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000007_0 Timed out after 600 secs
23/06/17 02:14:46 INFO mapreduce.Job:  map 29% reduce 0%
23/06/17 02:15:19 INFO mapreduce.Job:  map 48% reduce 0%
23/06/17 02:15:21 INFO mapreduce.Job:  map 52% reduce 0%
23/06/17 02:15:46 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000006_1, Status : FAILED
23/06/17 02:15:47 INFO mapreduce.Job:  map 32% reduce 0%
23/06/17 02:15:50 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000012_1, Status : FAILED
23/06/17 02:15:50 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000009_1, Status : FAILED
23/06/17 02:15:53 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000011_1, Status : FAILED
23/06/17 02:15:53 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000013_1, Status : FAILED
23/06/17 02:15:53 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000000_1, Status : FAILED
23/06/17 02:15:54 INFO mapreduce.Job:  map 29% reduce 0%
23/06/17 02:15:56 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000017_1, Status : FAILED
23/06/17 02:17:01 INFO mapreduce.Job:  map 29% reduce 3%
23/06/17 02:18:32 INFO mapreduce.Job:  map 26% reduce 3%
23/06/17 02:18:37 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000029_0, Status : FAILED
Container [pid=4268,containerID=container_1686987427129_0002_01_000031] is running beyond virtual memory limits. Current usage: 118.2 MB of 1 GB physical memory used; 3.6 GB of 2.1 GB virtual memory used. Killing container.
Dump of the process-tree for container_1686987427129_0002_01_000031 :
	|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
	|- 4272 4268 4268 4268 (java) 1098 221 1916653568 14942 /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.net.preferIPv4Stack=true -Dhadoop.metrics.log.level=WARN -Xmx200m -Djava.io.tmpdir=/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1686987427129_0002/container_1686987427129_0002_01_000031/tmp -Dlog4j.configuration=container-log4j.properties -Dyarn.app.container.log.dir=/usr/local/hadoop-2.7.6/logs/userlogs/application_1686987427129_0002/container_1686987427129_0002_01_000031 -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Dhadoop.root.logfile=syslog org.apache.hadoop.mapred.YarnChild 172.20.3.8 36095 attempt_1686987427129_0002_m_000029_0 31 
	|- 4268 4266 4268 4268 (bash) 1 3 13197312 382 /bin/bash -c /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.net.preferIPv4Stack=true -Dhadoop.metrics.log.level=WARN  -Xmx200m -Djava.io.tmpdir=/tmp/hadoop-root/nm-local-dir/usercache/root/appcache/application_1686987427129_0002/container_1686987427129_0002_01_000031/tmp -Dlog4j.configuration=container-log4j.properties -Dyarn.app.container.log.dir=/usr/local/hadoop-2.7.6/logs/userlogs/application_1686987427129_0002/container_1686987427129_0002_01_000031 -Dyarn.app.container.log.filesize=0 -Dhadoop.root.logger=INFO,CLA -Dhadoop.root.logfile=syslog org.apache.hadoop.mapred.YarnChild 172.20.3.8 36095 attempt_1686987427129_0002_m_000029_0 31 1>/usr/local/hadoop-2.7.6/logs/userlogs/application_1686987427129_0002/container_1686987427129_0002_01_000031/stdout 2>/usr/local/hadoop-2.7.6/logs/userlogs/application_1686987427129_0002/container_1686987427129_0002_01_000031/stderr  
	|- 4448 4272 4268 4268 (java) 0 1 1916653568 14942 N/A

Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

23/06/17 02:19:06 INFO mapreduce.Job:  map 29% reduce 3%
23/06/17 02:19:55 INFO mapreduce.Job:  map 31% reduce 3%
23/06/17 02:19:58 INFO mapreduce.Job:  map 32% reduce 3%
23/06/17 02:20:23 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000006_2, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000051 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34486 remote=pcvm606-8.emulab.net/172.20.6.8:42843]; Host Details : local host is: "slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8"; destination host is: "pcvm606-8.emulab.net":42843; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34486 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 15 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34486 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 18 more

23/06/17 02:20:24 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000011_2, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000054 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34490 remote=pcvm606-8.emulab.net/172.20.6.8:42843]; Host Details : local host is: "slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8"; destination host is: "pcvm606-8.emulab.net":42843; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34490 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 15 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34490 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 18 more

23/06/17 02:20:24 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000022_1, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000049 : java.net.SocketTimeoutException: Call From slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8 to pcvm603-8.emulab.net:37423 failed on socket timeout exception: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:44828 remote=pcvm603-8.emulab.net/172.20.3.8:37423]; For more details see:  http://wiki.apache.org/hadoop/SocketTimeout
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:751)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:44828 remote=pcvm603-8.emulab.net/172.20.3.8:37423]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at org.apache.hadoop.ipc.Client$Connection$PingInputStream.read(Client.java:521)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1085)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:980)

23/06/17 02:20:24 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000009_2, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000053 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34492 remote=pcvm606-8.emulab.net/172.20.6.8:42843]; Host Details : local host is: "slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8"; destination host is: "pcvm606-8.emulab.net":42843; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34492 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 15 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34492 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 18 more

23/06/17 02:20:24 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000012_2, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000052 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34488 remote=pcvm606-8.emulab.net/172.20.6.8:42843]; Host Details : local host is: "slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8"; destination host is: "pcvm606-8.emulab.net":42843; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34488 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 15 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34488 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 18 more

23/06/17 02:20:25 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000023_1, Status : FAILED
Container launch failed for container_1686987427129_0002_01_000050 : java.io.IOException: Failed on local exception: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34484 remote=pcvm606-8.emulab.net/172.20.6.8:42843]; Host Details : local host is: "slave1.hadoop-hvcf.mapreduce630.emulab.net/172.20.3.8"; destination host is: "pcvm606-8.emulab.net":42843; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1480)
	at org.apache.hadoop.ipc.Client.call(Client.java:1413)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy81.startContainers(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ContainerManagementProtocolPBClientImpl.startContainers(ContainerManagementProtocolPBClientImpl.java:96)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy82.startContainers(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$Container.launch(ContainerLauncherImpl.java:152)
	at org.apache.hadoop.mapreduce.v2.app.launcher.ContainerLauncherImpl$EventProcessor.run(ContainerLauncherImpl.java:375)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34484 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.ipc.Client$Connection$1.run(Client.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.handleSaslConnectionFailure(Client.java:651)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:738)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:376)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1529)
	at org.apache.hadoop.ipc.Client.call(Client.java:1452)
	... 15 more
Caused by: java.net.SocketTimeoutException: 60000 millis timeout while waiting for channel to be ready for read. ch : java.nio.channels.SocketChannel[connected local=/172.20.3.8:34484 remote=pcvm606-8.emulab.net/172.20.6.8:42843]
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:164)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at org.apache.hadoop.security.SaslRpcClient.saslConnect(SaslRpcClient.java:367)
	at org.apache.hadoop.ipc.Client$Connection.setupSaslConnection(Client.java:561)
	at org.apache.hadoop.ipc.Client$Connection.access$1900(Client.java:376)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:730)
	at org.apache.hadoop.ipc.Client$Connection$2.run(Client.java:726)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1758)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:726)
	... 18 more

23/06/17 02:22:47 INFO mapreduce.Job:  map 57% reduce 3%
23/06/17 02:22:48 INFO mapreduce.Job:  map 63% reduce 3%
23/06/17 02:22:51 INFO mapreduce.Job:  map 63% reduce 4%
23/06/17 02:22:54 INFO mapreduce.Job:  map 74% reduce 4%
23/06/17 02:22:56 INFO mapreduce.Job:  map 74% reduce 6%
23/06/17 02:22:58 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000019_1, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000019_1 Timed out after 600 secs
23/06/17 02:23:00 INFO mapreduce.Job:  map 58% reduce 6%
23/06/17 02:23:00 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000027_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000027_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000029
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000024_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000024_0 Timed out after 600 secs
Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000030_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000030_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000032
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000025_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000025_0 Timed out after 600 secs
Container killed on request. Exit code is 137
Container exited with a non-zero exit code 137
Killed by external signal

23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000014_1, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000014_1 Timed out after 600 secs
23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000023_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000023_0 Timed out after 600 secs
Container killed on request. Exit code is 137
Container exited with a non-zero exit code 137
Killed by external signal

23/06/17 02:23:04 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000022_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000022_0 Timed out after 600 secs
Container killed by the ApplicationMaster.
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143

23/06/17 02:23:05 INFO mapreduce.Job:  map 45% reduce 6%
23/06/17 02:23:06 INFO mapreduce.Job: Task Id : attempt_1686987427129_0002_m_000028_0, Status : FAILED
AttemptID:attempt_1686987427129_0002_m_000028_0 Timed out after 600 secs
Exception from container-launch.
Container id: container_1686987427129_0002_01_000030
Exit code: 66
Stack trace: ExitCodeException exitCode=66: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:585)
	at org.apache.hadoop.util.Shell.run(Shell.java:482)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:776)
	at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
	at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Container exited with a non-zero exit code 66

23/06/17 02:23:13 INFO mapreduce.Job:  map 45% reduce 14%
23/06/17 02:23:23 INFO mapreduce.Job:  map 48% reduce 14%
23/06/17 02:23:42 INFO mapreduce.Job:  map 48% reduce 16%
